app/__init__.py
from .app import create_app

app/app.py
from flask import Flask


def create_app(config=None):
    """Menginisiasi app untuk dijalankan oleh flask"""
    from . import routes

    app = Flask(__name__, template_folder="templates")
    if config is not None:
        if isinstance(config, dict):
            app.config.update(config)
        elif config.endswith('.py'):
            app.config.from_pyfile(config)
    else:
        app.config.from_pyfile("config.py")

    # models.init_app(app)
    routes.init_app(app)

    return app

app/routes/__init__.py
from .site import site


def init_app(app):
    app.register_blueprint(site)

app/routes/site.py
from flask import Blueprint, render_template, request, send_file
from tensorflow.keras.models import load_model
from tensorflow.keras.preprocessing.image import load_img, img_to_array
import numpy as np
import pickle
import jinja2

site = Blueprint('site', __name__)
UPLOAD_FOLDER = 'app/static/img'
QUESTIONS = [
    [{'id': 'q1', 'txt': 'Apakah anak Anda melihat Anda saat Anda memanggil namanya?'},
     {'id': 'q1a1', 'txt': 'Selalu'},
     {'id': 'q1a2', 'txt': 'Biasanya'},
     {'id': 'q1a3', 'txt': 'Kadang-kadang'},
     {'id': 'q1a4', 'txt': 'Jarang'},
     {'id': 'q1a5', 'txt': 'Tidak pernah'}],
    [{'id': 'q2', 'txt': 'Seberapa mudah Anda melakukan kontak mata dengan anak Anda?'},
     {'id': 'q2a1', 'txt': 'Sangat mudah'},
     {'id': 'q2a2', 'txt': 'Cukup mudah'},
     {'id': 'q2a3', 'txt': 'Cukup sulit'},
     {'id': 'q2a4', 'txt': 'Sangat sulit'},
     {'id': 'q2a5', 'txt': 'Tidak mungkin'}],
    [{'id': 'q3', 'txt': 'Seberapa sering anak Anda menunjuk untuk menunjukkan bahwa dia menginginkan sesuatu? (mis. '
                         'mainan yang di luar jangkauan)'},
     {'id': 'q3a1', 'txt': 'Berkali-kali sehari'},
     {'id': 'q3a2', 'txt': 'Beberapa kali sehari'},
     {'id': 'q3a3', 'txt': 'Beberapa kali seminggu'},
     {'id': 'q3a4', 'txt': 'Kurang dari sekali seminggu'},
     {'id': 'q3a5', 'txt': 'Tidak pernah'}],
    [{'id': 'q4', 'txt': 'Apakah anak Anda menunjukkan minat yang sama dengan Anda? (mis. menunjuk pemandangan yang '
                         'menarik)'},
     {'id': 'q4a1', 'txt': 'Berkali-kali sehari'},
     {'id': 'q4a2', 'txt': 'Beberapa kali sehari'},
     {'id': 'q4a3', 'txt': 'Beberapa kali seminggu'},
     {'id': 'q4a4', 'txt': 'Kurang dari sekali seminggu'},
     {'id': 'q4a5', 'txt': 'Tidak pernah'}],
    [{'id': 'q5', 'txt': 'Apakah anak Anda berpura-pura? (misalnya merawat boneka, berbicara di telepon mainan)'},
     {'id': 'q5a1', 'txt': 'Berkali-kali sehari'},
     {'id': 'q5a2', 'txt': 'Beberapa kali sehari'},
     {'id': 'q5a3', 'txt': 'Beberapa kali seminggu'},
     {'id': 'q5a4', 'txt': 'Kurang dari sekali seminggu'},
     {'id': 'q5a5', 'txt': 'Tidak pernah'}],
    [{'id': 'q6', 'txt': 'Apakah anak Anda mengikuti apa yang Anda lihat?'},
     {'id': 'q6a1', 'txt': 'Berkali-kali sehari'},
     {'id': 'q6a2', 'txt': 'Beberapa kali sehari'},
     {'id': 'q6a3', 'txt': 'Beberapa kali seminggu'},
     {'id': 'q6a4', 'txt': 'Kurang dari sekali seminggu'},
     {'id': 'q6a5', 'txt': 'Tidak pernah'}],
    [{'id': 'q7', 'txt': 'Jika Anda atau orang lain dalam keluarga terlihat kesal, apakah anak Anda menunjukkan '
                         'tanda-tanda ingin menghibur mereka? (misalnya membelai rambut, memeluknya)'},
     {'id': 'q7a1', 'txt': 'Selalu'},
     {'id': 'q7a2', 'txt': 'Biasanya'},
     {'id': 'q7a3', 'txt': 'Kadang-kadang'},
     {'id': 'q7a4', 'txt': 'Jarang'},
     {'id': 'q7a5', 'txt': 'Tidak pernah'}],
    [{'id': 'q8', 'txt': 'Maukah Anda menjelaskan kata-kata pertama anak Anda sebagai'},
     {'id': 'q8a1', 'txt': 'Sangat khas'},
     {'id': 'q8a2', 'txt': 'Cukup khas'},
     {'id': 'q8a3', 'txt': 'Sedikit tidak biasa'},
     {'id': 'q8a4', 'txt': 'Sangat tidak biasa'},
     {'id': 'q8a5', 'txt': 'Anak saya tidak berbicara'}],
    [{'id': 'q9', 'txt': 'Apakah anak Anda menggunakan gerakan sederhana? (mis. melambaikan tangan)'},
     {'id': 'q9a1', 'txt': 'Berkali-kali sehari'},
     {'id': 'q9a2', 'txt': 'Beberapa kali sehari'},
     {'id': 'q9a3', 'txt': 'Beberapa kali seminggu'},
     {'id': 'q9a4', 'txt': 'Kurang dari sekali seminggu'},
     {'id': 'q9a5', 'txt': 'Tidak pernah'}],
    [{'id': 'q10', 'txt': 'Apakah anak Anda tidak menatap apa pun (melamun) tanpa ada tujuan yang jelas?'},
     {'id': 'q10a1', 'txt': 'Berkali-kali sehari'},
     {'id': 'q10a2', 'txt': 'Beberapa kali sehari'},
     {'id': 'q10a3', 'txt': 'Beberapa kali seminggu'},
     {'id': 'q10a4', 'txt': 'Kurang dari sekali seminggu'},
     {'id': 'q10a5', 'txt': 'Tidak pernah'}],
]
ETHNICITY = [
    'Hispanic',
    'Latino',
    'Native indian',
    'Lainnya',
    'Pacifica',
    'White european',
    'Asian',
    'Black',
    'Middle eastern',
    'Mixed',
    'South asian',
]
ASSIGNER = ['Family member', 'Health care professional', 'Lainnya', 'Diri sendiri']
AGE = ['0-12', '13-23', '24-36']


@site.route('/')
def index():
    return render_template('home.jinja')


@site.route('/test-page')
def test_page():
    return render_template('test-page.jinja')


@site.route('/about')
def about():
    return render_template('about.jinja')


@site.route('/questionare-test')
def questionare_test():
    return render_template('questionare-test.jinja', questions=QUESTIONS)


@site.route('/image-test')
def image_test():
    return render_template('image-test.jinja')


@site.route('/result', methods=['POST'])
def result():
    form_data = request.form
    print(f"form: {form_data}")
    file = request.files
    print(f"file: {file}")
    print(f"form_data: {bool(form_data)}\nfile: {bool(file)}")
    if bool(form_data) and not bool(file):
        test_data = preprocess_data(form_data)
        print(f'test data = {test_data}')
        asd_model = pickle.load(open('asd_model/pkl_model.pkl', 'rb'))
        prob = asd_model.predict_proba([test_data])
        class_pred = np.argmax(prob[0])
        print(f"PROBABILITY: {prob}")
        answers = [form_data[key] for key in form_data if key.startswith('q')]
        questions = [q[0]['txt'] for q in QUESTIONS]
        qna = []
        for i in range(len(answers)):
            qna.append({
                'q': questions[i],
                'a': QUESTIONS[i][int(answers[i])]['txt']})

        bio = {
            'name': form_data['name'],
            'sex': 'Laki-laki' if form_data['sex'] == '1' else 'Perempuan',
            'ethnicity': ETHNICITY[int(form_data['ethnicity'])],
            'jaundice': 'Ya' if form_data['jaundice'] == '1' else 'Tidak',
            'family_mem_with_asd': 'Ya' if form_data['family_mem_with_asd'] == '1' else 'Tidak',
            'assigner': ASSIGNER[int(form_data['assigner'])],
            'age': AGE[int(form_data['age'])]
        }

        return render_template('result.jinja', type='form', class_pred=class_pred, confidence=prob[0][class_pred]*100, bio=bio, qna=qna)
    else:
        file = request.files["image"]
        upload_image_path = f"{UPLOAD_FOLDER}/{file.filename}"
        print(upload_image_path)
        file.save(upload_image_path)
        class_pred, conf = predict_image(upload_image_path)

        return render_template('result.jinja', type='image', class_pred=class_pred, confidence=conf*100, filename=file.filename)


def preprocess_data(data):
    # order of input: questions 1-10, sex, eth, jnd, fam, ass, 24_36, 0_12
    answers = [data[key] for key in data if key.startswith('q')]
    print(answers)
    for i in range(len(answers)):
        if i == len(answers) - 1:
            if answers[i] == '1' or answers[i] == '2' or answers[i] == '3':
                answers[i] = '1'
            else:
                answers[i] = '0'
        else:
            if answers[i] == '3' or answers[i] == '4' or answers[i] == '5':
                answers[i] = '1'
            else:
                answers[i] = '0'
    print(answers)
    test_data = [ans for ans in answers]
    # sex
    test_data.append(data['sex'])
    # ethnicity
    test_data.append(data['ethnicity'])
    # jaundice
    test_data.append(data['jaundice'])
    # family with asd
    test_data.append(data['family_mem_with_asd'])
    # assigner
    test_data.append(data['assigner'])
    # within 24_36
    test_data.append('1' if data['age'] == '2' else '0')
    # within 0_12
    test_data.append('1' if data['age'] == '0' else '0')

    return test_data


def predict_image(path_to_image):
    model = load_model('ASD_Model/Mobilenet-90.66.h5')
    image = load_img(path_to_image, target_size=(224, 224))
    img_array = img_to_array(image)
    img_array = np.expand_dims(img_array, axis=0)
    pred = model.predict(img_array)
    result = pred[0]
    print(f"Image prediction: {result}")
    answer = np.argmax(result)
    print(f"Answer: {answer}")
    return answer, result[answer]

app/templates/about.jinja
{% extends 'base.jinja' %}

{% block title %}
About - ASD Screening
{% endblock %}

{% block content %}
<div class="center">
    <div class="about">
        <h1>Apa itu ASD</h1>
        <p>Autism spectrum disorder (ASD) refers to a range of 
        conditions characterised by some degree of impaired social behaviour, 
        communication and language, and a narrow range of interests and activities 
        that are both unique to the individual and carried out repetitively</p>
        <div class="gambar-asd">
            <img src="/static/img/asd-behaviour.jpg" alt="" width="571" height="321">
        </div>
        <h1>Fakta Kunci</h1>
        <p>One in 160 children has an autism spectrum disorder (ASD)</p>
        <p>ASDs begin in childhood and tend to persist into adolescence and adulthood.</p>
        <p>While some people with ASD can live independently, others have severe disabilities and require life-long care and support.</p>
        <p>Evidence-based psychosocial interventions, such as behavioural treatment and parent skills training programmes, can reduce difficulties in communication and social behaviour, with a positive impact on well-being and quality of life for persons with ASD and their caregivers</p>
        <p>Interventions for people with ASD need to be accompanied by broader actions for making physical, social and attitudinal environments more accessible, inclusive and supportive</p>
        <p>Worldwide, people with ASD are often subject to stigma, discrimination and human rights violations. Globally, access to services and support for people with ASD is inadequate</p>
    </div>
</div>

{% endblock %}

app/templates/base.jinja
<!DOCTYPE html>
<html lang="en">
	<head>
		{% block head %}
		<!-- Required meta tags -->
		<meta charset="utf-8" />
		<meta
			name="viewport"
			content="width=device-width, initial-scale=1, shrink-to-fit=no"
        />
        
        <link rel="icon" href="/static/img/icon.svg">

		<!-- Bootstrap CSS -->
		<link
			rel="stylesheet"
			href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
			integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
			crossorigin="anonymous"
		/>

        <!-- Fonts -->
        <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@700&family=Roboto:wght@400;700&display=swap" rel="stylesheet">
		<link
			href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.1/css/all.min.css">
		<link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@700&family=Roboto:wght@400;700&display=swap" rel="stylesheet">

		<!-- Main Stylesheet -->
		<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css') }}">
		<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='style.css') }}">
        <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='other.css') }}">

		<title>{% block title %}{% endblock %}</title>
		{% endblock %}
	</head>
	<body>
		<div class="wrapper">
            <!-- Start of Desktop Navigation -->
            <nav class="desktop-nav">
                <div class="logo">
                    <a href="/">
                        <img src="/static/img/Logo.png" alt="">
                    </a>
                </div>

                <div class="menu-items">
                    <li>
                        <a href="/">Home</a>
                    </li>
                    <li>
                        <a href="about">About</a>
                    </li>
                    <li>
                        <a href="{{ url_for('site.test_page') }}" class="btn">Ikuti Tes</a>
                    </li>
                </div>
            </nav>
            <!-- End of Desktop Navigation -->

            <!-- Start of Hero Section -->
            <div class="hero-container">
                {% block content %} {% endblock %}
            </div>
            <!-- End of Hero Section -->
        </div>

        <footer>
            <div class="wrapper">
                <div class="footer-container">

                    <div class="asdfoot">
                        <a href="/">
                            <img src="/static/img/LogoFoot.png" alt="" />
                        </a>
                    </div>

                    <div class="csipb">
                        <a href="https://cs.ipb.ac.id">
                            <img src="/static/img/csipb.png" alt="" />
                        </a>
                    </div>

                    <div class="footer-nav">
                        <h3>Made by:</h3>
                        <ul>
                            <li><a href="https://www.instagram.com/rizhaaf/">Rizha Alfajri</a> -
                                <a href="https://www.instagram.com/muftialroaz/">Mufti Alfarokhul Azam</a></li>
                            <li><a href="https://www.instagram.com/elsam219/">Elia Samuel</a> -
                                <a href="https://www.instagram.com/fahrezahafiz/">Fahreza Ikhsan Hafiz</a></li>
                            <li><a href="https://www.instagram.com/julchristoper_/">Julius Christoper Siswanto</a></li>
                        </ul>
                    </div>

                </div>
            </div>
        </footer>

		<!-- Optional JavaScript -->
		{# <script>
			document.addEventListener('click', function (event) {
				if (!event.target.matches('#not-implemented-yet')) return;
				event.preventDefault();
				alert("Not Implemented yet !");
			}, false);
		</script>  #}
		<!-- jQuery first, then Popper.js, then Bootstrap JS -->
		<script
			src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
			integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
			crossorigin="anonymous"
		></script>
		<script
			src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
			integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
			crossorigin="anonymous"
		></script>
		<script
			src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
			integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
			crossorigin="anonymous"
		></script>

		<script
			src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.1/js/all.min.js">
		</script>
	</body>
</html>

app/templates/home.jinja
{% extends 'base.jinja' %}

{% block title %}
ASD Screening
{% endblock %}

{% block content %}

<div class="home">
    <div class="left">
        <h1>Autism Spectrum
            Disorder Screening</h1>
        <p>Autism spectrum disorder (ASD) atau yang lebih sering disebut autisme merupakan
            gangguan perkembangan saraf yang memengaruhi perkembangan bahasa
            dan kemampuan seorang anak untuk berkomunikasi, berinteraksi, serta berperilaku.
            Kenali gejala autisme pada anak dengan mengikuti test di bawah ini!</p>
        <a href="{{ url_for('site.test_page') }}" class="btn">Ikuti Tes</a>
        <a href="{{ url_for('site.about') }}" class="btn cyan">Tentang ASD</a>
    </div>

    <div class="right">
        <img src="/static/img/HeroImage.png" alt="">
    </div>
</div>

{% endblock %}

app/templates/image-test.jinja
{% extends 'base.jinja' %}

{% block title %}
Image Test - ASD Screening
{% endblock %}

{% block content %}
<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='imgtest.css') }}">

<script class="jsbin" type="text/javascript" src="{{url_for('static', filename='imgtest.js') }}"></script>
<script class="jsbin" src="https://ajax.googleapis.com/ajax/libs/jquery/1/jquery.min.js"></script>

<div class="center">
    <div class="form">

        <h1>Tes Foto Diagnosa Autisme</h1>

        <form action="{{ url_for('site.result') }}" accept-charset="utf-8" method="post" enctype="multipart/form-data" >
            <div class="file-upload">
                <button class="file-upload-btn" type="button" onclick="$('.file-upload-input').trigger( 'click' )">Tambah Foto</button>
                
                <div class="image-upload-wrap">
                    <input class="file-upload-input" id="image" name="image" type='file' onchange="readURL(this);" accept="image/*" required="" oninvalid="this.setCustomValidity('Silahkan upload foto')">
                    <div class="drag-text">
                        <h3>Drag dan drop foto<h3>
                        </div>
                    </div>

                    <div class="file-upload-content">
                        <img class="file-upload-image" src="#" alt="your image" />
                        <div class="image-title-wrap">
                            <button type="button" onclick="removeUpload()" class="remove-image">Hapus <span class="image-title">Uploaded Image</span></button>
                        </div>
                    </div>
                </div>
                <p><input class="btn" type="submit" name="btnSubmit" value="Lihat Hasilnya"></p>
        </form>

    </div>
        
</div>
{% endblock %}

app/templates/questionare-test.jinja
{% extends 'base.jinja' %}

{% block title %}
Questionare Test - ASD Screening
{% endblock %}
{% block content %}
<div class="center">
    <h1>Tes Kuesioner Diagnosa Autisme</h1>
    <form action="{{ url_for('site.result') }}" accept-charset="utf-8" method="post">
        <h3>Data Diri</h3>
        <div class="card">
            <div class="form-check">
            <div class="nama">
                <h2>Nama</h2>
                <input type="text" class="form-control" placeholder="Nama" id="name" name="name" required>
            </div>
            </div>
            <div class="data-diri">
                <div class="data">
                    {# Jenis Kelamin #}
                    <div class="form-check">
                        <h2 class="atas">Jenis Kelamin</h2>
                        <div class="flex">
                            <li>
                                <label class="radio" for="jk1">
                                <input type="radio" required id="jk1" name="sex" value="1">
                                Laki-laki </label>
                            </li>
                            <li>
                                <label class="radio" for="jk2">
                                <input type="radio" required id="jk2" name="sex" value="0">
                                Perempuan </label>
                            </li>
                        </div>
                    </div>
                    {# Kelompok Etnik #}
                    <div class="form-check">
                        <h2>Kelompok etnik</h2>
                        <select name="ethnicity" id="ethnicity" class="form-select" aria-label="Default select example" required>
                            <option value="">Pilih kelompok etnik</option>
                            <option value="0">Hispanic</option>
                            <option value="1">Latino</option>
                            <option value="2">Native indian</option>
                            <option value="4">Pacifica</option>
                            <option value="5">White european</option>
                            <option value="6">Asian</option>
                            <option value="7">Black</option>
                            <option value="8">Middle eastern</option>
                            <option value="9">Mixed</option>
                            <option value="10">South asian</option>
                            <option value="3">Lainnya</option>
                        </select>
                    </div>
                    {# Penyakit Kuning #}
                    <div class="form-check">
                        <h2>Pernah terkena penyakit kuning?</h2>
                        <div class="flex">
                            <li>
                                <label class="radio" for="pk1">
                                <input type="radio" required id="pk1" name="jaundice" value="1">
                                Pernah</label>
                            </li>
                            <li>
                                <label class="radio" for="pk2">
                                <input type="radio" required id="pk2" name="jaundice" value="0">
                                Tidak pernah </label>
                            </li>
                        </div>
                    </div>
                </div>
                <div class="data">
                    {# Ada keluarga dengan ASD? #}
                    <div class="form-check">
                        <h2 class="atas">Ada keluarga dengan ASD?</h2>
                        <div class="flex">
                            <li>
                                <label class="radio" for="asd1">
                                <input type="radio" required id="asd1" name="family_mem_with_asd" value="1">
                                Ya </label>
                            </li>
                            <li>
                                <label class="radio" for="asd2">
                                <input type="radio" required id="asd2" name="family_mem_with_asd" value="0">
                                Tidak </label>
                            </li>
                        </div>
                    </div>
                    {# Kelompok assigner #}
                    <div class="form-check">
                        <h2>Assigner</h2>
                        <select name="assigner" id="assigner" class="form-select" aria-label="Default select example" required>
                            <option value="">Pilih assigner</option>
                            <option value="0">Family member</option>
                            <option value="1">Health care professional</option>
                            <option value="2">Lainnya</option>
                            <option value="3">Diri sendiri</option>
                        </select>
                    </div>
                    {# Penyakit Kuning #}
                    <div class="form-check">
                        <h2>Umur (bulan)</h2>
                        <div class="flex">
                            <li>
                                <label class="radio" for="umur1">
                                <input type="radio" required id="age0" name="age" value="0">
                                0-12</label>
                            </li>
                            <li>
                                <label class="radio" for="umur2">
                                <input type="radio" required id="age1" name="age" value="1">
                                13-23 </label>
                            </li>
                            <li>
                                <label class="radio" for="umur3">
                                <input type="radio" required id="age2" name="age" value="2">
                                24-36 </label>
                            </li>
                        </div>
                    </div>

                </div>

            </div>

        </div>

        <h3>Kuesioner</h3>
        {% for i in range(questions|length) %}
            <div class="card">
                <div class="form-check">
                    <h2>{{ i+1 }}. {{ questions[i][0]['txt'] }}</h2>
                    {% for j in range(5) %}
                        <li>
                            <label class="radio" for="{{ questions[i][j+1]['id'] }}">
                            <input type="radio" required id="{{ questions[i][j+1]['id'] }}" name="{{ questions[i][0]['id'] }}" value="{{ j+1 }}">
                            {{ questions[i][j+1]['txt'] }} </label>
                        </li>
                    {% endfor %}
                </div>
            </div>
        {% endfor %}
        <div class="content has-text-centered mt-5">
            <p><input class="btn" type="submit" name="btnSubmit" value="Lihat Hasilnya"></p>
        </div>
    </form>
</div>
{% endblock %}

app/templates/result.jinja
{% extends 'base.jinja' %}

{% block title %}
Result - ASD Screening
{% endblock %}

{% block content %}

<div class="center">
    <div class="hasil">
        <h1>Hasil Tes</h1>
        {% if type == 'form' %}
            <div class="card">
                {# <div class="data"> #}
                    <h3>Data Diri</h3>
                    <div class="form-check">
                        <div class="row">
                            <div class="col-sm">
                                <h2>Nama</h2>
                                <h2 class="atas">Jenis Kelamin</h2>
                                {# Kelompok Etnik #}
                                <h2>Kelompok etnik</h2>
                                {# Penyakit Kuning #}
                                <h2>Pernah terkena penyakit kuning?</h2>
                                {# Ada keluarga dengan ASD? #}
                                <h2 class="atas">Ada keluarga dengan ASD?</h2>
                                {# Kelompok assigner #}
                                <h2>Assigner</h2>
                                {# Penyakit Kuning #}
                                <h2>Umur (bulan)</h2>
                            </div>
                            <div class="col-sm">
                                <h2>{{ bio.name }}</h2>
                                <h2>{{ bio.sex }}</h2>
                                <h2>{{ bio.ethnicity }}</h2>
                                <h2>{{ bio.jaundice }}</h2>
                                <h2>{{ bio.family_mem_with_asd }}</h2>
                                <h2>{{ bio.assigner }}</h2>
                                <h2>{{ bio.age }}</h2>
                            </div>
                        </div>
                    </div>

                    <h3>Kuesioner</h3>
                    <div class="form-check">
                        {% for item in qna %}
                            <h2>{{ item.q }}</h2>
                            <p>{{ item.a }}</p>
                        {% endfor %}
                    </div>

                    <h3>Hasil</h3>
                    <div class="form-check">
                        {% if class_pred == 1 %}
                            <h2 style="color:red">Anak Anda memiliki kemungkinan {{ '%0.2f'| format(confidence|float) }}% mengalami Autism Spectrum Disorder<h2>
                            <h2>Kunjungi dokter Anda untuk diagnosis dan tindakan lebih lanjut</h2>
                        {% else %}
                            <h2 style="color:green">Anak Anda memiliki kemungkinan {{ '%0.2f'| format(confidence|float) }}% tidak mengalami Autism Spectrum Disorder<h2>
                        {% endif %}
                    </div>
            </div>
            {% else %}
                <div class="card">
                    <div class="form-check">
                        <div class="col-sm">
                            <img src="{{ url_for('static', filename='img/' + filename) }}"" width="500">
                            {% if class_pred == 1 %}
                                <h2 style="color:red">Anak Anda memiliki kemungkinan {{ '%0.2f'| format(confidence|float) }}% mengalami Autism Spectrum Disorder<h2>
                                <h2>Kunjungi dokter Anda untuk diagnosis dan tindakan lebih lanjut</h2>
                            {% else %}
                                <h2 style="color:green">Anak Anda memiliki kemungkinan {{ '%0.2f'| format(confidence|float) }}% tidak mengalami Autism Spectrum Disorder<h2>
                            {% endif %}
                        </div>
                    </div>
                </div>
        {% endif %}
        <div class="testlagi">
            {% if type == 'form' %}
                <a href="{{ url_for('site.test_page') }}" class="btn btn-primary">Tes Lagi</a>
            {% else %}
                <a href="{{ url_for('site.test_page') }}" class="btn btn-primary">Tes Lagi</a>
            {% endif %}
        </div>
        <div class="testlagi"></div>
    </div>
</div>

{% endblock %}

app/templates/test-page.jinja
{% extends 'base.jinja' %}

{% block title %}
Test Option - ASD Screening
{% endblock %}

{% block content %}
{# CSS from other.css #}


<div class="center">
<h1>Pilih Opsi Tes</h1>
</div>

    <div class="opsi-test">
        <div class="card" style="width: 18rem;">
            <img src="/static/img/childAva.png" class="card-img-top" alt="...">
            <div class="card-body">
                <h5 class="card-title">Tes Foto</h5>
                <p class="card-text">Melakukan tes autisme melalui foto anak yang diupload.</p>
                <div style="text-align: center">
                    <a href="{{ url_for('site.image_test') }}" class="btn btn-primary text-center">Pilih</a>
                </div>
            </div>
        </div>

        <div class="card" style="width: 18rem;">
            <img src="/static/img/Question.png" class="card-img-top" alt="...">
            <div class="card-body">
                <h5 class="card-title">Tes Kuesioner</h5>
                <p class="card-text">Mengisi pertanyaan mengenai karakteristik dan kebiasaan anak.</p>
                <div style="text-align: center">
                    <a href="{{ url_for('site.questionare_test') }}" class="btn btn-primary">Pilih</a>
                </div>
            </div>
        </div>
    </div>




{% endblock %}